[package]
name = "tasker_model"
version.workspace = true
edition.workspace = true

[lib]
crate-type = [ "cdylib", "rlib" ]

[lints]
workspace = true

[dependencies]
serde.workspace = true
hdi.workspace = true
