/* This file is generated by zits. Do not edit manually */

import {GetItemsInput, HashInfo, MyLinkFilter, TypedAnchor, } from './path-explorer.types';
import {
/** types.ts */
HoloHash,
AgentPubKey,
DnaHash,
WasmHash,
EntryHash,
ActionHash,
AnyDhtHash,
ExternalHash,
KitsuneAgent,
KitsuneSpace,
HoloHashB64,
AgentPubKeyB64,
DnaHashB64,
WasmHashB64,
EntryHashB64,
ActionHashB64,
AnyDhtHashB64,
InstalledAppId,
Signature,
CellId,
DnaProperties,
RoleName,
InstalledCell,
Timestamp,
Duration,
HoloHashed,
NetworkInfo,
FetchPoolInfo,
/** hdk/action.ts */
SignedActionHashed,
ActionHashed,
ActionType,
Action,
NewEntryAction,
Dna,
AgentValidationPkg,
InitZomesComplete,
CreateLink,
DeleteLink,
OpenChain,
CloseChain,
Update,
Delete,
Create,
/** hdk/capabilities.ts */
CapSecret,
CapClaim,
GrantedFunctionsType,
GrantedFunctions,
ZomeCallCapGrant,
CapAccess,
CapGrant,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
DhtOpType,
DhtOp,
getDhtOpType,
getDhtOpAction,
getDhtOpEntry,
getDhtOpSignature,
/** hdk/entry.ts */
EntryVisibility,
AppEntryDef,
EntryType,
EntryContent,
Entry,
/** hdk/record.ts */
Record as HcRecord,
RecordEntry as HcRecordEntry,
/** api/admin/types.ts */
InstalledAppInfoStatus,
DeactivationReason,
DisabledAppReason,
StemCell,
ProvisionedCell,
ClonedCell,
CellType,
CellInfo,
AppInfo,
MembraneProof,
FunctionName,
ZomeName,
ZomeDefinition,
IntegrityZome,
CoordinatorZome,
DnaDefinition,
ResourceBytes,
ResourceMap,
CellProvisioningStrategy,
CellProvisioning,
DnaVersionSpec,
DnaVersionFlexible,
AppRoleDnaManifest,
AppRoleManifest,
AppManifest,
AppBundle,
AppBundleSource,
NetworkSeed,
ZomeLocation,
   } from '@holochain/client';

import {
/** Common */
DhtOpHashB64,
DhtOpHash,
/** DnaFile */
DnaFile,
DnaDef,
Zomes,
WasmCode,
/** entry-details */
EntryDetails,
RecordDetails,
Details,
DetailsType,
EntryDhtStatus,
/** Validation */
ValidationStatus,
ValidationReceipt,
   } from '@holochain-open-dev/core-types';

/** User defined external dependencies */
import {ItemLink, SweepInterval, SweepResponse} from './deps.types';

import {ZomeProxy} from '@ddd-qc/lit-happ';
import {pathExplorerFunctionNames} from './path-explorer.fn';

/**
 *
 */
export class PathExplorerProxy extends ZomeProxy {
  static readonly DEFAULT_ZOME_NAME = "zPathExplorer"
  static readonly FN_NAMES = pathExplorerFunctionNames
 
  async getAllItemsFromAnchor(leafAnchor: string): Promise<ItemLink[]> {
    return this.call('get_all_items_from_anchor', leafAnchor);
  }

  async getAllItems(hash: Uint8Array): Promise<ItemLink[]> {
    return this.call('get_all_items', hash);
  }

  async getAllItemsFromB64(b64: Uint8Array): Promise<ItemLink[]> {
    return this.call('get_all_items_from_b64', b64);
  }

  async getAllRootAnchors(): Promise<TypedAnchor[]> {
    return this.call('get_all_root_anchors', null);
  }

  async getItems(input: GetItemsInput): Promise<ItemLink[]> {
    return this.call('get_items', input);
  }

  async getLeafs(ta: TypedAnchor): Promise<TypedAnchor[]> {
    return this.call('get_leafs', ta);
  }

  async getTypedAnchor(anchor: string): Promise<[EntryHashB64, TypedAnchor | null]> {
    return this.call('get_typed_anchor', anchor);
  }

  async getTypedChildren(parentTa: TypedAnchor): Promise<TypedAnchor[]> {
    return this.call('get_typed_children', parentTa);
  }

  async inspectLink(any: Uint8Array): Promise<HashInfo> {
    return this.call('inspect_link', any);
  }



  async getAgentEntryHash(): Promise<Uint8Array> {
    return this.call('get_agent_entry_hash', null);
  }
}
